// This file is automatically generated. DO NOT EDIT.

/* eslint-disable */

export const PACKAGE_INFO = {
  "name": "m8",
  "version": "0.0.1",
  "author": "RA Sewell <richard.sewell@ncoderz.com>",
  "license": "BSD-2-Clause",
  "description": "Programmers helpful command line mate"
};
